<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation.Physics\Simulation.Physics.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
